services:
  postgres:
    image: postgres
    container_name: JakartaEELabsDB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: JakartaEELabs
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

# If you want to connect to DB via terminal
# > docker exec -it JakartaEELabsDB /bin/bash
# > psql -U admin -d JakartaEELabs